const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--disable-gpu'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
    const base = process.env.PREVIEW_BASE_URL;
    await context.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const page = await context.newPage();
    const failures = [];
    let failNextModelTest = false;
    page.on('pageerror', error => failures.push(error.message));
    await page.route('**/api/ai/services/gemini-primary/test', async route => {
      if (!failNextModelTest) return route.continue();
      failNextModelTest = false;
      await route.fulfill({ status: 429, contentType: 'application/json', body: JSON.stringify({ error: 'rate_limited' }) });
    });
    await page.goto(`${base}/admin/services`);
    await expect(page.getByRole('heading', { name: '服务中心', exact: true })).toBeVisible();
    await expect(page.getByRole('tab', { name: 'API 接入' })).toHaveAttribute('aria-selected', 'true');
    await page.goto(`${base}/admin/services?tab=ai`);
    await expect(page.getByRole('tab', { name: 'API 接入' })).toHaveAttribute('aria-selected', 'true');
    await expect(page.getByRole('tab', { name: '网站收藏' })).toHaveAttribute('aria-selected', 'false');
    const geminiCard = page.locator('[data-ai-service="gemini-primary"]');
    await expect(geminiCard).toBeVisible();
    await expect(geminiCard.locator('.ai-service-card-summary')).toContainText('个模型');
    await expect(geminiCard.getByLabel('API Base URL')).not.toBeVisible();
    await geminiCard.locator('.ai-service-config summary').click();
    await expect(geminiCard.getByLabel('API Base URL')).toBeVisible();
    await expect(page.locator('.ai-service-binding-group')).toHaveCount(2);
    await expect(page.locator('.ai-service-binding-group').filter({ has: page.getByRole('heading', { name: '对话与助手' }) }).locator('[data-ai-binding]')).toHaveCount(3);
    await expect(page.locator('.ai-service-binding-group').filter({ has: page.getByRole('heading', { name: '媒体生成' }) }).locator('[data-ai-binding]')).toHaveCount(2);
    const chatBinding = page.locator('[data-ai-binding="chat"]');
    await expect(chatBinding.getByRole('option', { name: 'Gemini' })).toHaveCount(1);
    await geminiCard.getByLabel('API Base URL').fill('http://127.0.0.1:8317/v1');
    await geminiCard.getByLabel('API Key').fill('integration-only-do-not-leak');
    await expect(geminiCard.getByRole('button', { name: '测试连接' })).toBeDisabled();
    await geminiCard.getByRole('button', { name: '保存设置' }).click();
    await expect(geminiCard.getByText('已配置', { exact: true })).toBeVisible();
    await expect(geminiCard.getByLabel('API Base URL')).toHaveValue('http://127.0.0.1:8317/v1');
    await expect(geminiCard.getByLabel('API Key')).toHaveValue('');
    await geminiCard.getByRole('button', { name: '测试连接' }).click();
    await expect(geminiCard.getByRole('status')).toContainText('A 模型列表读取通过');
    const modelCatalog = page.locator('.ai-service-catalog');
    await modelCatalog.getByLabel('模型目录服务').selectOption('gemini-primary');
    await expect(modelCatalog.locator('.ai-service-catalog-list li')).toHaveCount(2);
    await expect(modelCatalog.locator('.ai-service-catalog-list')).toHaveCSS('max-height', '420px');
    await modelCatalog.getByLabel('搜索模型').fill('gemini-preview-fast');
    await expect(modelCatalog.locator('.ai-service-catalog-list li')).toHaveCount(1);
    await expect(modelCatalog.getByText('gemini-preview-fast', { exact: true })).toBeVisible();
    await expect(modelCatalog.getByText('输入上限 64,000 tokens')).toBeVisible();
    await modelCatalog.getByLabel('搜索模型').fill('');
    failNextModelTest = true;
    await geminiCard.getByRole('button', { name: '测试连接' }).click();
    await expect(geminiCard.getByText('上游服务限流，请稍后重试。', { exact: true })).toBeVisible();
    await expect(geminiCard.getByText(/A 模型列表读取通过/)).toHaveCount(0);
    const planBinding = page.locator('[data-ai-binding="plan_assistant"]');
    await planBinding.getByLabel('今日计划建议 模型').selectOption('gemini-preview-fast');
    await planBinding.getByRole('button', { name: '保存绑定' }).click();
    await expect(planBinding.getByRole('status')).toContainText('已保存');
    await expect(planBinding.getByRole('button', { name: 'B 测试所选模型生成' })).not.toBeVisible();
    await planBinding.locator('.ai-service-assistant-tests summary').click();
    await planBinding.getByRole('button', { name: 'B 测试所选模型生成' }).click();
    await expect(planBinding.getByText(/B 文本生成通过/)).toContainText('gemini-preview-fast');
    await planBinding.getByRole('button', { name: 'C 测试助手结构' }).click();
    await expect(planBinding.getByText(/C 结构化校验通过/)).toContainText('Gemini 原生结构化输出');
    await expect(planBinding.getByText(/B 文本生成通过/)).toBeVisible();
    await planBinding.getByLabel('今日计划建议 模型').selectOption('gemini-preview-listed-first');
    await expect(planBinding.getByText(/B 文本生成通过/)).toHaveCount(0);
    await expect(planBinding.getByText(/C 结构化校验通过/)).toHaveCount(0);

    const videoBinding = page.locator('[data-ai-binding="video_assistant"]');
    await videoBinding.getByLabel('视频创意助手 模型').selectOption('gemini-preview-fast');
    await videoBinding.getByRole('button', { name: '保存绑定' }).click();
    await videoBinding.locator('.ai-service-assistant-tests summary').click();
    await videoBinding.getByRole('button', { name: 'B 测试所选模型生成' }).click();
    await expect(videoBinding.getByText(/B 文本生成通过/)).toContainText('gemini-preview-fast');
    await videoBinding.getByRole('button', { name: 'C 测试助手结构' }).click();
    await expect(videoBinding.getByText(/C 结构化校验通过/)).toContainText('Gemini 原生结构化输出');
    const stored = await page.evaluate(() => JSON.stringify(Object.entries(localStorage)));
    const testKey = 'integration-only-do-not-leak';
    assert(!stored.includes(testKey), 'API keys must not be persisted in localStorage');
    assert(!stored.includes('Authorization'), 'Authorization must not be persisted in localStorage');
    const rendered = await page.evaluate(() => [document.body.innerText, ...Array.from(document.querySelectorAll('input')).flatMap(input => [input.value, input.placeholder])].join('\n'));
    assert(!rendered.includes(testKey), 'API keys must never appear in rendered text or input values');
    await page.getByRole('tab', { name: '网站收藏' }).click();
    await expect(page.getByRole('tab', { name: '网站收藏' })).toHaveAttribute('aria-selected', 'true');
    await expect(page.locator('.service-card')).toHaveCount(2);
    await expect(page.getByRole('button', { name: /^全部\s*2$/ })).toHaveAttribute('aria-pressed', 'true');
    await page.keyboard.press('Control+k');
    await expect(page.getByRole('searchbox', { name: '搜索网站' })).toBeFocused();
    const cpa = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: 'CodexProxy · CPA' }) });
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('href', 'https://lancoai.site:9445/management.html#/login');
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('rel', 'noopener noreferrer');
    await expect(cpa.locator('.service-count')).toHaveText('待检测');
    await expect(cpa.getByRole('button', { name: '接口', exact: true })).toHaveCount(0);
    await cpa.locator('summary').click();
    await expect(cpa.locator('details')).toHaveAttribute('open', '');
    await expect(cpa.locator('.service-model-empty')).toContainText('尚未检测模型');
    await expect(cpa.locator('summary')).toContainText('提供的模型');
    await cpa.locator('summary').click();
    await cpa.getByRole('button', { name: '复制 API 地址' }).click();
    assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'https://lancoai.site:9445/v1');
    await page.getByRole('button', { name: '添加网站' }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByLabel('服务名称', { exact: true }).fill('家庭 NAS');
    await page.getByLabel('网站地址', { exact: true }).fill('http://192.168.1.20:5000/');
    await page.getByLabel('服务用途', { exact: true }).fill('备份和文件管理');
    await page.getByRole('button', { name: '保存网站' }).click();
    await expect(page.locator('.service-card')).toHaveCount(3);
    await page.reload();
    const nas = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS', exact: true }) });
    await expect(nas).toBeVisible();
    await nas.getByRole('button', { name: '编辑', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByLabel('服务名称', { exact: true }).fill('家庭 NAS 已编辑');
    await page.getByRole('button', { name: '保存网站' }).click();
    const edited = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS 已编辑', exact: true }) });
    await expect(edited).toBeVisible();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('家庭');
    await expect(page.locator('.service-card')).toHaveCount(1);
    await edited.getByRole('button', { name: '删除', exact: true }).click();
    await edited.getByRole('button', { name: '确认删除', exact: true }).click();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('');
    await expect(page.locator('.service-card')).toHaveCount(2);
    await expect(page.locator('.services-monitor')).toHaveCount(0);
    await expect(page.locator('.service-status')).toHaveCount(0);
    await expect(page.getByText('一个入口，找到所有服务', { exact: true })).toHaveCount(0);
    await expect(page.locator('.service-card footer')).toHaveCount(0);
    await expect(cpa.locator('.service-card-actions').getByRole('link', { name: '打开网站' })).toBeVisible();
    await page.getByRole('button', { name: '刷新收藏列表', exact: true }).click();
    await expect(page.locator('.services-feedback')).toHaveText('收藏列表已刷新');
    await page.screenshot({ path: '/tmp/lanco-services-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile must not scroll horizontally');
    await page.screenshot({ path: '/tmp/lanco-services-mobile.png', fullPage: true });
    const another = await browser.newContext();
    await another.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const second = await another.newPage();
    await second.goto(`${base}/admin/services?tab=websites`);
    await expect(second.locator('.service-card')).toHaveCount(2);
    assert.deepEqual(failures, []);
    console.log('Services: CRUD, reload persistence, separate browser, links, clipboard, search and mobile passed');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
