const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--disable-gpu'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
    const base = process.env.PREVIEW_BASE_URL;
    await context.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const page = await context.newPage();
    const failures = [];
    page.on('pageerror', error => failures.push(error.message));
    await page.goto(`${base}/admin/services`);
    await expect(page.getByRole('heading', { name: '服务中心', exact: true })).toBeVisible();
    await expect(page.locator('.service-card')).toHaveCount(2);
    await expect(page.getByRole('button', { name: /^全部\s*2$/ })).toHaveAttribute('aria-pressed', 'true');
    await page.keyboard.press('Control+k');
    await expect(page.getByRole('searchbox', { name: '搜索网站' })).toBeFocused();
    const cpa = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: 'CodexProxy · CPA' }) });
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('href', 'https://lancoai.site:9445/management.html#/login');
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('rel', 'noopener noreferrer');
    await expect(cpa.locator('.service-count')).toHaveText('2');
    await expect(cpa.getByRole('button', { name: '接口', exact: true })).toHaveCount(0);
    await cpa.locator('summary').click();
    await expect(cpa.locator('details')).toHaveAttribute('open', '');
    await expect(cpa.locator('details p')).toContainText('POST /v1/chat/completions');
    await cpa.locator('summary').click();
    await cpa.getByRole('button', { name: '复制 API 地址' }).click();
    assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'https://lancoai.site:9445/v1');
    await page.getByRole('button', { name: '添加网站' }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByLabel('服务名称', { exact: true }).fill('家庭 NAS');
    await page.getByLabel('网站地址', { exact: true }).fill('http://192.168.1.20:5000/');
    await page.getByLabel('服务用途', { exact: true }).fill('备份和文件管理');
    await page.getByRole('button', { name: '保存网站' }).click();
    await expect(page.locator('.service-card')).toHaveCount(3);
    await page.reload();
    const nas = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS', exact: true }) });
    await expect(nas).toBeVisible();
    await nas.getByRole('button', { name: '编辑', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByLabel('服务名称', { exact: true }).fill('家庭 NAS 已编辑');
    await page.getByRole('button', { name: '保存网站' }).click();
    const edited = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS 已编辑', exact: true }) });
    await expect(edited).toBeVisible();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('家庭');
    await expect(page.locator('.service-card')).toHaveCount(1);
    await edited.getByRole('button', { name: '删除', exact: true }).click();
    await edited.getByRole('button', { name: '确认删除', exact: true }).click();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('');
    await expect(page.locator('.service-card')).toHaveCount(2);
    await expect(page.locator('.services-monitor-heading').getByText('尚未接入', { exact: true })).toBeVisible();
    await expect(page.locator('.services-metric')).toHaveCount(4);
    await expect(page.locator('.service-status')).toHaveCount(0);
    await expect(page.getByText('一个入口，找到所有服务', { exact: true })).toHaveCount(0);
    await expect(page.locator('.service-card footer')).toHaveCount(0);
    await expect(cpa.locator('.service-card-actions').getByRole('link', { name: '打开网站' })).toBeVisible();
    await page.getByRole('button', { name: '刷新收藏列表', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('收藏列表已刷新');
    await page.screenshot({ path: '/tmp/lanco-services-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile must not scroll horizontally');
    await page.screenshot({ path: '/tmp/lanco-services-mobile.png', fullPage: true });
    const another = await browser.newContext();
    await another.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const second = await another.newPage();
    await second.goto(`${base}/admin/services`);
    await expect(second.locator('.service-card')).toHaveCount(2);
    assert.deepEqual(failures, []);
    console.log('Services: CRUD, reload persistence, separate browser, links, clipboard, search and mobile passed');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
