const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--disable-gpu'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
    const base = process.env.PREVIEW_BASE_URL;
    const gateway = process.env.PREVIEW_OPENAI_BASE_URL;
    assert(gateway, 'the preview must expose its loopback OpenAI-compatible gateway');
    await context.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const page = await context.newPage();
    const failures = [];
    let failNextModelTest = false;
    page.on('pageerror', error => failures.push(error.message));
    await page.route('**/api/ai/services/chat-primary/test', async route => {
      if (!failNextModelTest) return route.continue();
      failNextModelTest = false;
      await route.fulfill({ status: 429, contentType: 'application/json', body: JSON.stringify({ error: 'rate_limited' }) });
    });
    await page.goto(`${base}/admin/services`);
    await expect(page.getByRole('heading', { name: '服务中心', exact: true })).toBeVisible();
    await expect(page.getByRole('tab')).toHaveCount(0);
    await expect(page.getByRole('heading', { name: 'API 接入', level: 2 })).toBeVisible();
    await expect(page.getByRole('heading', { name: '网站收藏', level: 2 })).toBeVisible();
    await expect(page.locator('.service-card')).toHaveCount(2);

    await expect(page.locator('[data-ai-service]')).toHaveCount(2);
    await expect(page.locator('[data-ai-service="gemini-primary"]')).toHaveCount(0);
    await expect(page.getByText(/Gemini 原生/)).toHaveCount(0);
    const chatCard = page.locator('[data-ai-service="chat-primary"]');
    const mediaCard = page.locator('[data-ai-service="media-primary"]');
    await expect(chatCard.locator('.ai-service-use')).toHaveText(['AI 对话', '今日计划建议', '视频创意助手']);
    await expect(mediaCard.locator('.ai-service-use')).toHaveText(['文生图', '图生视频']);
    await expect(chatCard.locator('.ai-service-card-summary')).toContainText('0 个模型');
    await expect(chatCard.getByRole('button', { name: '查看模型' })).toBeDisabled();
    await expect(chatCard.getByLabel('API Base URL')).not.toBeVisible();
    await chatCard.locator('.ai-service-config summary').click();
    await expect(chatCard.getByLabel('API Base URL')).toBeVisible();

    const assistants = page.locator('#assistant-models');
    await expect(assistants.locator('[data-ai-binding]')).toHaveCount(2);
    await expect(page.locator('[data-ai-binding="chat"]')).toHaveCount(0);
    await expect(page.getByLabel('今日计划建议 服务')).toHaveCount(0);
    await expect(assistants.locator('.ai-service-secret-state')).toHaveText('已选 0/2');
    const planBinding = page.locator('[data-ai-binding="plan_assistant"]');
    const videoBinding = page.locator('[data-ai-binding="video_assistant"]');
    await expect(planBinding.locator('.ai-service-binding-via')).toHaveText('经 Chat API');
    await expect(planBinding.locator('.ai-service-binding-hint')).toHaveText('未选择模型');

    await chatCard.getByLabel('API Base URL').fill(gateway);
    await chatCard.getByLabel('API Key').fill('integration-only-do-not-leak');
    await expect(chatCard.getByRole('button', { name: '测试连接' })).toBeDisabled();
    await chatCard.getByRole('button', { name: '保存设置' }).click();
    await expect(chatCard.getByText('已配置', { exact: true })).toBeVisible();
    await expect(chatCard.getByLabel('API Base URL')).toHaveValue(gateway);
    await expect(chatCard.getByLabel('API Key')).toHaveValue('');
    await chatCard.getByRole('button', { name: '测试连接' }).click();
    await expect(chatCard.getByRole('status')).toContainText('A 模型列表读取通过 · 2 个');
    await expect(chatCard.locator('.ai-service-card-summary')).toContainText('2 个模型');

    const modelCatalog = page.locator('.ai-service-catalog');
    await expect(modelCatalog).not.toHaveAttribute('open', '');
    await expect(modelCatalog.locator('summary')).toContainText('Chat API · 2');
    await chatCard.getByRole('button', { name: '查看模型' }).click();
    await expect(modelCatalog).toHaveAttribute('open', '');
    await expect(modelCatalog.getByLabel('模型目录服务')).toHaveValue('chat-primary');
    await expect(modelCatalog.locator('.ai-service-catalog-list li')).toHaveCount(2);
    await expect(modelCatalog.locator('.ai-service-catalog-list')).toHaveCSS('max-height', '420px');
    await modelCatalog.getByLabel('搜索模型').fill('preview-chat-fast');
    await expect(modelCatalog.locator('.ai-service-catalog-list li')).toHaveCount(1);
    await expect(modelCatalog.getByText('preview-chat-fast', { exact: true })).toBeVisible();
    await expect(modelCatalog.getByText('上下文上限 64,000 tokens')).toBeVisible();
    await modelCatalog.getByLabel('模型目录服务').selectOption('media-primary');
    await expect(modelCatalog.getByLabel('搜索模型')).toHaveValue('');
    await expect(modelCatalog.locator('.ai-service-catalog-empty')).toContainText('尚未读取模型列表');
    await modelCatalog.locator('summary').click();
    await expect(modelCatalog).not.toHaveAttribute('open', '');

    failNextModelTest = true;
    await chatCard.getByRole('button', { name: '测试连接' }).click();
    await expect(chatCard.getByText('上游服务限流，请稍后重试。', { exact: true })).toBeVisible();
    await expect(chatCard.getByText(/A 模型列表读取通过/)).toHaveCount(0);

    await planBinding.getByLabel('今日计划建议 模型').selectOption('preview-chat-fast');
    await expect(planBinding.locator('.ai-service-binding-hint')).toHaveText('未保存');
    await planBinding.getByRole('button', { name: '保存模型' }).click();
    await expect(planBinding.getByRole('status')).toContainText('已保存');
    await expect(planBinding.locator('.ai-service-binding-hint')).toHaveCount(0);
    await expect(planBinding.getByRole('button', { name: '保存模型' })).toBeDisabled();
    await expect(planBinding.getByRole('button', { name: 'B 测试所选模型生成' })).not.toBeVisible();
    await planBinding.locator('.ai-service-assistant-tests summary').click();
    await planBinding.getByRole('button', { name: 'B 测试所选模型生成' }).click();
    await expect(planBinding.getByText(/B 文本生成通过/)).toContainText('chat-primary / preview-chat-fast');
    await planBinding.getByRole('button', { name: 'C 测试助手结构' }).click();
    await expect(planBinding.getByText(/C 结构化校验通过/)).toContainText('JSON Schema 支持');
    await expect(planBinding.getByText(/B 文本生成通过/)).toBeVisible();
    await planBinding.getByLabel('今日计划建议 模型').selectOption('preview-chat-listed-first');
    await expect(planBinding.getByText(/B 文本生成通过/)).toHaveCount(0);
    await expect(planBinding.getByText(/C 结构化校验通过/)).toHaveCount(0);
    await planBinding.getByLabel('今日计划建议 模型').selectOption('preview-chat-fast');
    await expect(planBinding.locator('.ai-service-binding-hint')).toHaveCount(0);

    await videoBinding.getByLabel('视频创意助手 模型').selectOption('preview-chat-fast');
    await videoBinding.getByRole('button', { name: '保存模型' }).click();
    await expect(videoBinding.getByRole('status')).toContainText('已保存');
    await videoBinding.locator('.ai-service-assistant-tests summary').click();
    await videoBinding.getByRole('button', { name: 'B 测试所选模型生成' }).click();
    await expect(videoBinding.getByText(/B 文本生成通过/)).toContainText('preview-chat-fast');
    await videoBinding.getByRole('button', { name: 'C 测试助手结构' }).click();
    await expect(videoBinding.getByText(/C 结构化校验通过/)).toContainText('JSON Schema 支持');
    await expect(assistants.locator('.ai-service-secret-state')).toHaveText('已选 2/2');

    const stored = await page.evaluate(() => JSON.stringify(Object.entries(localStorage)));
    const testKey = 'integration-only-do-not-leak';
    assert(!stored.includes(testKey), 'API keys must not be persisted in localStorage');
    assert(!stored.includes('Authorization'), 'Authorization must not be persisted in localStorage');
    const rendered = await page.evaluate(() => [document.body.innerText, ...Array.from(document.querySelectorAll('input')).flatMap(input => [input.value, input.placeholder])].join('\n'));
    assert(!rendered.includes(testKey), 'API keys must never appear in rendered text or input values');

    await expect(page.getByRole('button', { name: /^全部\s*2$/ })).toHaveAttribute('aria-pressed', 'true');
    await page.keyboard.press('Control+k');
    await expect(page.getByRole('searchbox', { name: '搜索网站' })).toBeFocused();
    const cpa = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: 'CodexProxy · CPA' }) });
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('href', 'https://lancoai.site:9445/management.html#/login');
    await expect(cpa.getByRole('link', { name: '打开网站' })).toHaveAttribute('rel', 'noopener noreferrer');
    await expect(cpa.locator('.service-count')).toHaveText('待检测');
    await expect(cpa.getByRole('button', { name: '接口', exact: true })).toHaveCount(0);
    await cpa.locator('summary').click();
    await expect(cpa.locator('details')).toHaveAttribute('open', '');
    await expect(cpa.locator('.service-model-empty')).toContainText('尚未检测模型');
    await expect(cpa.locator('summary')).toContainText('提供的模型');
    await cpa.locator('summary').click();
    await cpa.getByRole('button', { name: '复制 API 地址' }).click();
    assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'https://lancoai.site:9445/v1');
    const editor = page.getByRole('dialog');
    await page.getByRole('button', { name: '添加网站' }).click();
    await expect(editor).toBeVisible();
    await editor.getByLabel('服务名称', { exact: true }).fill('家庭 NAS');
    await editor.getByLabel('网站地址', { exact: true }).fill('http://192.168.1.20:5000/');
    await editor.getByLabel('服务用途', { exact: true }).fill('备份和文件管理');
    await editor.getByRole('button', { name: '保存网站' }).click();
    await expect(page.locator('.service-card')).toHaveCount(3);
    await page.reload();
    const nas = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS', exact: true }) });
    await expect(nas).toBeVisible();
    await expect(page.locator('[data-ai-service="chat-primary"] .ai-service-card-summary')).toContainText('2 个模型');
    await expect(planBinding.getByLabel('今日计划建议 模型')).toHaveValue('preview-chat-fast');
    await nas.getByRole('button', { name: '编辑', exact: true }).click();
    await expect(editor).toBeVisible();
    await editor.getByLabel('服务名称', { exact: true }).fill('家庭 NAS 已编辑');
    await editor.getByRole('button', { name: '保存网站' }).click();
    const edited = page.locator('.service-card').filter({ has: page.getByRole('heading', { name: '家庭 NAS 已编辑', exact: true }) });
    await expect(edited).toBeVisible();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('家庭');
    await expect(page.locator('.service-card')).toHaveCount(1);
    await edited.getByRole('button', { name: '删除', exact: true }).click();
    await edited.getByRole('button', { name: '确认删除', exact: true }).click();
    await page.getByRole('searchbox', { name: '搜索网站' }).fill('');
    await expect(page.locator('.service-card')).toHaveCount(2);
    await expect(page.locator('.services-monitor')).toHaveCount(0);
    await expect(page.locator('.service-status')).toHaveCount(0);
    await expect(page.getByText('一个入口，找到所有服务', { exact: true })).toHaveCount(0);
    await expect(page.locator('.service-card footer')).toHaveCount(0);
    await expect(cpa.locator('.service-card-actions').getByRole('link', { name: '打开网站' })).toBeVisible();
    await page.getByRole('button', { name: '刷新收藏列表', exact: true }).click();
    await expect(page.locator('.services-feedback')).toHaveText('收藏列表已刷新');
    await page.screenshot({ path: '/tmp/lanco-services-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 1024, height: 900 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'tablet must not scroll horizontally');
    await page.screenshot({ path: '/tmp/lanco-services-tablet.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile must not scroll horizontally');
    await page.screenshot({ path: '/tmp/lanco-services-mobile.png', fullPage: true });

    const another = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await another.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const legacy = await another.newPage();
    await legacy.goto(`${base}/admin/services?tab=websites`);
    await expect(legacy.locator('.service-card')).toHaveCount(2);
    await expect(legacy).toHaveURL(/\/admin\/services#websites$/);
    await expect.poll(() => legacy.locator('#websites').evaluate(element => Math.round(element.getBoundingClientRect().top))).toBeLessThan(120);
    const anchored = await another.newPage();
    await anchored.goto(`${base}/admin/services#assistant-models`);
    await expect(anchored.locator('[data-ai-binding="video_assistant"]')).toBeVisible();
    await expect.poll(() => anchored.locator('#assistant-models').evaluate(element => Math.round(element.getBoundingClientRect().top))).toBeLessThan(120);
    await expect(anchored.getByLabel('视频创意助手 模型')).toHaveValue('preview-chat-fast');
    assert.deepEqual(failures, []);
    console.log('Services: single page, Chat API A/B/C tests, model catalog, bookmarks CRUD, reload persistence, old links and mobile passed');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
