const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');

async function main() {
  const base = process.env.PREVIEW_BASE_URL;
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  const evidence = { assertions: [], externalRequests: [], pageErrors: [] };
  try {
    const context = await browser.newContext();
    await context.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    context.on('request', request => { if (!request.url().startsWith(base) && !request.url().startsWith('data:')) evidence.externalRequests.push(request.url()); });
    await context.route('**/api/chat/settings', route => route.fulfill({ json: { temperature: 0.7, api_key_configured: true } }));
    await context.route('**/api/chat/models', route => route.fulfill({ json: [{ id: 'preview-model', name: 'Preview model' }] }));
    const create = async (name, goal) => {
      const response = await context.request.post(`${base}/api/chat/projects`, { data: { name, goal, instructions: '' } });
      assert.equal(response.status(), 200);
      return response.json();
    };
    const alpha = await create('AI 与存储', '能解释存储原理，并通过小实验验证。');
    const beta = await create('论文阅读', '形成对研究问题与方法局限的判断。');
    await create('长名称项目：持续练习听说读写并追踪需要反复练习的错误', '雅思语言练习');
    const page = await context.newPage();
    page.on('pageerror', error => evidence.pageErrors.push(error.message));
    const trigger = page.getByRole('button', { name: /^选择学习项目：/ });
    const dialog = page.getByRole('dialog', { name: '选择学习项目', exact: true });
    for (const width of [390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(`${base}/__react/?view=chat`);
      await expect(trigger).toBeEnabled();
      await expect(trigger).toHaveAccessibleName('选择学习项目：自由对话');
      await trigger.click();
      await expect(dialog).toBeVisible();
      await expect(dialog.getByRole('searchbox', { name: '搜索学习项目' })).toBeFocused();
      await expect(dialog.getByRole('button', { name: '自由对话', exact: true })).toHaveAttribute('aria-pressed', 'true');
      await dialog.getByRole('searchbox').fill('方法局限');
      await expect(dialog.getByRole('button', { name: '选择项目 论文阅读', exact: true })).toBeVisible();
      await expect(dialog.getByRole('button', { name: '选择项目 AI 与存储', exact: true })).toHaveCount(0);
      await dialog.getByRole('searchbox').fill('不存在的目标');
      await expect(dialog.getByText('没有匹配的项目')).toBeVisible();
      await dialog.getByRole('searchbox').fill('');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      const rect = await dialog.boundingBox();
      assert.ok(rect.x >= 0 && rect.width <= width && Math.abs(rect.x + rect.width / 2 - width / 2) < 2);
      if (process.env.CLAUDE_PROJECT_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.CLAUDE_PROJECT_SCREENSHOTS, `projects-${width}.jpg`), type: 'jpeg', quality: 65 });
      await page.keyboard.press('Escape');
      await expect(dialog).toHaveCount(0);
      await expect(trigger).toBeFocused();
      evidence.assertions.push(`${width}px centered searchable cards/name+goal/empty state/free selection/no overflow/Escape focus`);
    }
    await page.getByLabel('聊天消息').fill('保留未发送草稿');
    await trigger.click();
    await dialog.getByRole('button', { name: '自由对话', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByLabel('聊天消息')).toHaveValue('保留未发送草稿');
    evidence.assertions.push('current selection closes without resetting draft');
    await trigger.click();
    page.once('dialog', native => native.dismiss());
    await dialog.getByRole('button', { name: '选择项目 AI 与存储', exact: true }).click();
    await expect(dialog).toBeVisible();
    await expect(trigger).toHaveAccessibleName('选择学习项目：自由对话');
    await expect(page.getByLabel('聊天消息')).toHaveValue('保留未发送草稿');
    page.once('dialog', native => native.accept());
    await dialog.getByRole('button', { name: '选择项目 AI 与存储', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toHaveAccessibleName('选择学习项目：AI 与存储');
    await expect(page.locator('.workspace-goal')).toHaveText(alpha.goal);
    await expect(page.getByLabel('聊天消息')).toHaveValue('');
    await expect(page.getByRole('button', { name: '项目记忆', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: '项目目标', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: /论文资料/ })).toBeEnabled();
    evidence.assertions.push('cancelled draft discard stays open/current; confirmed switch preserves goal/memory/papers actions');
    const conversation = await (await context.request.post(`${base}/api/chat/conversations`, { data: { project_id: alpha.id } })).json();
    await page.goto(`${base}/__react/?view=chat&conversation=${conversation.id}`);
    await expect(trigger).toHaveAccessibleName('选择学习项目：AI 与存储');
    await page.route(`**/api/chat/conversations/${conversation.id}`, async route => {
      if (route.request().method() === 'PATCH') await route.fulfill({ status: 503, json: { error: 'unavailable' } });
      else await route.continue();
    });
    await page.getByLabel('聊天消息').fill('失败时保留的草稿');
    await trigger.click();
    await dialog.getByRole('button', { name: '选择项目 论文阅读', exact: true }).click();
    await expect(dialog).toBeVisible();
    await expect(trigger).toHaveAccessibleName('选择学习项目：AI 与存储');
    await expect(page.getByLabel('聊天消息')).toHaveValue('失败时保留的草稿');
    await expect(dialog.getByRole('button', { name: '选择项目 AI 与存储', exact: true })).toHaveAttribute('aria-pressed', 'true');
    evidence.assertions.push('failed real draft save keeps selected project/conversation/draft and picker open');
    let releaseSave;
    const saving = new Promise(resolve => { releaseSave = resolve; });
    await page.unroute(`**/api/chat/conversations/${conversation.id}`);
    await page.route(`**/api/chat/conversations/${conversation.id}`, async route => {
      if (route.request().method() === 'PATCH') { await saving; await route.continue(); }
      else await route.continue();
    });
    await dialog.getByRole('button', { name: '选择项目 论文阅读', exact: true }).click();
    await expect(trigger).toBeDisabled();
    await expect(dialog.getByRole('button', { name: '自由对话', exact: true })).toBeDisabled();
    await expect(dialog.getByRole('button', { name: '选择项目 AI 与存储', exact: true })).toBeDisabled();
    releaseSave();
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toHaveAccessibleName('选择学习项目：论文阅读');
    await expect(page.locator('.workspace-goal')).toHaveText(beta.goal);
    evidence.assertions.push('pending save disables trigger/cards; completed save switches and closes');
    await trigger.focus();
    await page.keyboard.press('Enter');
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button', { name: '新建学习项目', exact: true }).click();
    const editor = page.getByRole('dialog', { name: '新建学习项目', exact: true });
    await expect(editor).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    await trigger.click();
    await dialog.getByRole('button', { name: '新建学习项目', exact: true }).click();
    await editor.getByLabel('项目名称', { exact: true }).fill('新项目');
    await editor.getByLabel('想达到什么目标', { exact: true }).fill('新目标');
    await editor.getByRole('button', { name: '保存项目', exact: true }).click();
    await expect(editor).toHaveCount(0);
    await expect(trigger).toHaveAccessibleName('选择学习项目：新项目');
    await expect(page.locator('.workspace-goal')).toHaveText('新目标');
    await trigger.click();
    await dialog.getByRole('button', { name: '自由对话', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toHaveAccessibleName('选择学习项目：自由对话');
    await expect(page.locator('.workspace-goal')).toHaveCount(0);
    await expect(page.getByRole('button', { name: /论文资料/ })).toBeDisabled();
    await trigger.click();
    await dialog.getByRole('button', { name: '关闭窗口', exact: true }).click();
    await expect(trigger).toBeFocused();
    evidence.assertions.push('keyboard open/create uses existing editor/cancel+save focus/free switch/close focus');
    assert.deepEqual(evidence.externalRequests, []);
    assert.deepEqual(evidence.pageErrors, []);
    if (process.env.CLAUDE_PROJECT_EVIDENCE) fs.writeFileSync(`${process.env.CLAUDE_PROJECT_EVIDENCE}/project-browser.json`, JSON.stringify(evidence, null, 2) + '\n');
    await context.close();
    console.log(`PASS: project selector (${evidence.assertions.length} assertions, no external requests or page errors)`);
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
