const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { expect } = require('@playwright/test');
const base = process.env.PREVIEW_BASE_URL;

async function main() {
  if (process.env.REACT_SHOP_SCREENSHOT_DIR) fs.mkdirSync(process.env.REACT_SHOP_SCREENSHOT_DIR, { recursive: true });
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  try {
    const context = await browser.newContext();
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    const page = await context.newPage();
    await page.goto(`${base}/`);
    await expect(page.getByRole('heading', { name: '暂无商品' })).toBeVisible();
    const admin = await browser.newContext();
    await admin.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const manager = await admin.newPage();
    await manager.goto(`${base}/admin/shop`);
    await expect(manager.getByRole('heading', { name: /^商品管理/ })).toBeVisible();
    await expect(manager.locator('.shop-admin-product')).toHaveCount(5);
    await expect(manager.locator('.shop-admin-product h3')).toHaveCount(5);
    await expect(manager.locator('.shop-admin-row')).toHaveCount(7);
    await expect(manager.locator('.shop-admin-product').first().locator('.shop-admin-row')).toHaveCount(2);
    await expect(manager.locator('.topbar-right').getByRole('button', { name: '刷新来源' })).toBeVisible();
    await expect(manager.locator('.topbar-right').getByRole('button', { name: '重新读取' })).toBeVisible();
    await expect(manager.locator('.shop-admin-savebar').getByRole('button', { name: '保存商品设置' })).toBeVisible();
    await expect(manager.getByText('独立售价 · 人工确认与交付')).toHaveCount(0);
    await expect(manager.getByText('成本仅管理员可见。新规格默认草稿，填写售价并勾选上架后才会展示给客户。来源刷新不会覆盖售价。')).toHaveCount(0);
    await expect(manager.getByLabel('售价 2:7')).toBeVisible();
    const adminSnapshot = await (await manager.request.get(`${base}/api/v1/shop/admin`)).json();
    const sameTitleItem = { ...adminSnapshot.items[0], product_id: '99', key: '99:1' };
    await manager.route('**/api/v1/shop/admin', route => route.request().method() === 'GET' ? route.fulfill({ json: { ...adminSnapshot, items: [...adminSnapshot.items, sameTitleItem] } }) : route.continue());
    await manager.getByRole('button', { name: '重新读取' }).click();
    await expect(manager.locator('.shop-admin-product')).toHaveCount(6);
    await expect(manager.locator('.shop-admin-row')).toHaveCount(8);
    await expect(manager.getByLabel('售价 99:1')).toBeVisible();
    await manager.unroute('**/api/v1/shop/admin');
    await manager.getByRole('button', { name: '重新读取' }).click();
    await expect(manager.locator('.shop-admin-product')).toHaveCount(5);
    await manager.getByLabel('售价 2:7').focus();
    await manager.keyboard.press('Tab');
    await expect(manager.getByLabel('上架 2:7')).toBeFocused();
    await manager.getByLabel('商家 Telegram 用户名').fill('shop_owner');
    await manager.getByLabel('售价 2:7').fill('1100.01');
    await expect(manager.getByLabel('售价 2:2')).toHaveValue('');
    await manager.getByLabel('上架 2:7').check();
    await manager.getByLabel('售价 2:2').fill('1200.02');
    await manager.getByLabel('上架 2:2').check();
    await manager.getByLabel('售价 1:4').fill('130.00');
    await manager.getByLabel('上架 1:4').check();
    await manager.getByRole('button', { name: '保存商品设置' }).focus();
    await manager.keyboard.press('Enter');
    await expect(manager.getByRole('status')).toContainText('已保存');
    await page.goto(`${base}/?product=2`);
    await expect(page.getByRole('button', { name: '加入购物车', exact: true })).toBeVisible();
    const response = await page.request.get(`${base}/api/v1/shop/catalog`);
    assert.equal(response.status(), 200);
    const publicText = await response.text();
    assert.equal(/cost_cents|qiangyunai|source_url|cnadsiuvhga/.test(publicText), false);
    await manager.locator('.shop-copy-editor summary').first().click();
    await manager.getByLabel('商品说明 2').fill('<img src=x onerror=alert(1)>\n商家自填说明');
    await manager.getByLabel('售后条款 2').fill('本店售后请联系商家确认。');
    await manager.getByRole('button', { name: '保存商品设置' }).click();
    await expect(manager.getByRole('status')).toContainText('已保存');
    for (const width of [390, 768, 1440]) {
      await manager.setViewportSize({ width, height: 900 });
      assert.equal(await manager.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      await manager.getByLabel('售价 1:4').scrollIntoViewIfNeeded();
      await manager.getByLabel('售价 1:4').focus();
      const clearance = await manager.evaluate(() => {
        const field = document.activeElement.getBoundingClientRect();
        const bar = document.querySelector('.shop-admin-savebar').getBoundingClientRect();
        const save = document.querySelector('.shop-admin-savebar button').getBoundingClientRect();
        const launcher = document.querySelector('.lanco-agent-launcher').getBoundingClientRect();
        return { fieldBottom: field.bottom, barTop: bar.top, saveRight: save.right, launcherLeft: launcher.left };
      });
      assert.ok(clearance.fieldBottom <= clearance.barTop && clearance.saveRight <= clearance.launcherLeft, JSON.stringify({ width, clearance }));
      await manager.evaluate(() => scrollTo(0, 0));
      await page.setViewportSize({ width, height: 900 });
      await page.goto(`${base}/`);
      await page.getByRole('link', { name: 'ChatGPT Pro 200', exact: true }).click();
      await expect(page).toHaveURL(/product=2/);
      await expect(page.getByRole('heading', { name: '商品说明', exact: true })).toBeVisible();
      await expect(page.getByText('<img src=x onerror=alert(1)>', { exact: false })).toBeVisible();
      await expect(page.locator('.shop-detail-copy img')).toHaveCount(0);
      await page.getByRole('button', { name: '续费卡密不可新开', exact: true }).click();
      await page.getByLabel('购买数量', { exact: true }).fill('3');
      await expect(page.getByTestId('purchase-total')).toHaveText('¥3600.06');
      await page.getByRole('button', { name: '立即购买', exact: true }).click();
      const dialog = page.getByRole('dialog', { name: '购买信息' });
      await expect(dialog.getByLabel('可复制的购买信息')).toHaveValue(/合计：¥3600.06 CNY/);
      await dialog.getByRole('button', { name: '复制购买信息' }).click();
      await expect(dialog).toContainText('购买信息已复制');
      assert.match(await page.evaluate(() => navigator.clipboard.readText()), /合计：¥3600.06 CNY/);
      if (process.env.REACT_SHOP_SCREENSHOT_DIR) await page.screenshot({ path: path.join(process.env.REACT_SHOP_SCREENSHOT_DIR, `checkout-${width}.png`), fullPage: true });
      await page.keyboard.press('Escape');
      await expect(dialog).toHaveCount(0);
      await expect(page.getByRole('button', { name: '立即购买', exact: true })).toBeFocused();
      await page.getByLabel('购买数量', { exact: true }).fill('0');
      await expect(page.getByRole('button', { name: '加入购物车', exact: true })).toBeDisabled();
      await page.getByLabel('购买数量', { exact: true }).fill('3');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      const detailLayout = await page.evaluate(() => {
        const image = document.querySelector('.shop-detail-image').getBoundingClientRect();
        const info = document.querySelector('.shop-detail-info').getBoundingClientRect();
        return { imageRight: image.right, imageBottom: image.bottom, infoLeft: info.left, infoTop: info.top };
      });
      if (width >= 1000) assert.ok(detailLayout.imageRight <= detailLayout.infoLeft, JSON.stringify(detailLayout));
      if (width < 720) assert.ok(detailLayout.imageBottom <= detailLayout.infoTop, JSON.stringify(detailLayout));
      const shots = process.env.REACT_SHOP_SCREENSHOT_DIR;
      if (shots) {
        fs.mkdirSync(shots, { recursive: true });
        await page.screenshot({ path: path.join(shots, `detail-${width}.png`), fullPage: true });
        await manager.screenshot({ path: path.join(shots, `admin-copy-${width}.png`), fullPage: true });
      }
      await page.getByRole('button', { name: '加入购物车', exact: true }).click();
      await page.getByRole('button', { name: '加入购物车', exact: true }).click();
      await page.getByRole('link', { name: /^购物车（/ }).click();
      await expect(page).toHaveURL(/view=cart/);
      await expect(page.getByLabel('数量 2:2', { exact: true })).toHaveValue('6');
      await page.reload();
      await expect(page.getByTestId('cart-total')).toHaveText('¥7200.12');
      const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('hysteria.shop.cart.v1')));
      assert.deepEqual(persisted, [{ id: '2:2', quantity: 6 }]);
      if (shots) await page.screenshot({ path: path.join(shots, `cart-${width}.png`), fullPage: true });
      await page.goBack();
      await expect(page.getByRole('button', { name: '加入购物车', exact: true })).toBeVisible();
      await page.goForward();
      await expect(page.getByRole('heading', { name: '购物车', exact: true })).toBeVisible();
      await page.getByLabel('数量 2:2', { exact: true }).fill('2');
      await expect(page.getByTestId('cart-total')).toHaveText('¥2400.04');
      await page.getByRole('button', { name: '清空购物车' }).click();
      await expect(page.getByRole('heading', { name: '购物车还是空的' })).toBeVisible();
    }
    // Multiple SKUs, fresh prices, and a failure must never expose a stale summary.
    await page.goto(`${base}/?product=2`);
    await page.getByRole('button', { name: '加入购物车', exact: true }).click();
    await page.getByRole('button', { name: '续费卡密不可新开', exact: true }).click();
    await page.getByRole('button', { name: '加入购物车', exact: true }).click();
    await page.getByRole('link', { name: /^购物车（/ }).click();
    const fresh = JSON.parse(publicText);
    fresh.products[0].variants[0].price_cents = 150001;
    let catalogMode = 'fresh';
    let releaseRequest;
    await page.route('**/api/v1/shop/catalog', async route => {
      if (catalogMode === 'held') await new Promise(resolve => { releaseRequest = resolve; });
      if (catalogMode === 'failure') return route.fulfill({ status: 503, json: {} });
      const value = structuredClone(fresh);
      if (catalogMode === 'removed') value.products = [];
      if (catalogMode === 'soldout') value.products[0].variants[0].available = false;
      if (catalogMode === 'stale') value.status = 'stale';
      if (catalogMode === 'no-contact') value.telegram = '';
      await route.fulfill({ json: value });
    });
    await page.getByRole('button', { name: '确认购买信息' }).click();
    await expect(page.getByLabel('可复制的购买信息')).toHaveValue(/合计：¥2700.03 CNY/);
    fresh.products[0].variants[0].price_cents = 160001;
    await page.getByRole('button', { name: '复制购买信息' }).click();
    await expect(page.getByRole('dialog')).toContainText('商品价格或联系方式已更新');
    await expect(page.getByLabel('可复制的购买信息')).toHaveValue(/合计：¥2800.03 CNY/);
    await page.keyboard.press('Escape');
    for (const mode of ['failure', 'removed', 'soldout', 'stale', 'no-contact']) {
      catalogMode = mode;
      await page.getByRole('button', { name: '确认购买信息' }).click();
      await expect(page.getByRole('dialog')).toContainText('本次购买未生成');
      await expect(page.getByRole('link', { name: '联系商家 Telegram' })).toHaveCount(0);
      await expect(page.getByLabel('可复制的购买信息')).toHaveCount(0);
      await page.keyboard.press('Escape');
    }
    catalogMode = 'held';
    await page.getByRole('button', { name: '确认购买信息' }).click();
    await expect(page.getByRole('dialog')).toContainText('正在核对');
    await expect.poll(() => typeof releaseRequest).toBe('function');
    await page.keyboard.press('Escape');
    await page.getByRole('link', { name: '商品目录', exact: true }).first().click();
    catalogMode = 'fresh'; releaseRequest();
    await expect(page.getByRole('heading', { name: '商品目录', exact: true })).toBeVisible();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.unroute('**/api/v1/shop/catalog');
    await page.getByRole('searchbox', { name: '搜索商品' }).fill('nothing');
    await expect(page.getByRole('heading', { name: '没有匹配的商品' })).toBeVisible();
    await page.evaluate(() => localStorage.setItem('hysteria.shop.cart.v1', JSON.stringify([{ id: '2:7', quantity: 99, price: 1 }, { id: '2:7', quantity: 99 }, { id: '2:2', quantity: 0 }, { id: 'evil', quantity: 2 }])));
    await page.goto(`${base}/?view=cart`);
    await expect(page.getByLabel('数量 2:7', { exact: true })).toHaveValue('99');
    await expect(page.locator('.shop-cart-row')).toHaveCount(1);
    await expect(page.getByTestId('cart-total')).toHaveText('¥108900.99');
    await page.getByRole('button', { name: '移除 2:7', exact: true }).click();
    await expect(page.getByRole('heading', { name: '购物车还是空的' })).toBeVisible();
    await page.goto(`${base}/?product=99999`);
    await expect(page.getByRole('heading', { name: '商品不存在或已下架' })).toBeVisible();
    await page.goto(`${base}/?product=1`);
    await expect(page.getByRole('button', { name: '加入购物车', exact: true })).toBeDisabled();
    // Refresh/revision failures preserve both kinds of merchant drafts.
    await manager.getByLabel('售价 2:7').fill('999.99');
    await manager.getByLabel('商品说明 2').fill('未保存的商家说明');
    const changedCost = { ...adminSnapshot, items: adminSnapshot.items.map(item => item.key === '2:7' ? { ...item, cost_cents: item.cost_cents + 200 } : item) };
    await manager.route('**/api/v1/shop/refresh', route => route.fulfill({ json: changedCost }));
    await manager.getByRole('button', { name: '刷新来源' }).click();
    await expect(manager.getByRole('status')).toContainText('售价和未保存输入已保留');
    await expect(manager.getByLabel('售价 2:7')).toHaveValue('999.99');
    await expect(manager.getByLabel('商品说明 2')).toHaveValue('未保存的商家说明');
    await expect(manager.locator('.shop-admin-product').first()).toContainText('¥1002.00');
    await manager.unroute('**/api/v1/shop/refresh');
    await manager.route('**/api/v1/shop/admin', route => route.request().method() === 'PUT' ? route.fulfill({ status: 409, json: { error: 'revision_conflict' } }) : route.continue());
    await manager.getByRole('button', { name: '保存商品设置' }).click();
    await expect(manager.getByRole('alert')).toContainText('设置已被其他页面修改');
    await expect(manager.getByLabel('售价 2:7')).toHaveValue('999.99');
    await expect(manager.getByLabel('商品说明 2')).toHaveValue('未保存的商家说明');
    manager.once('dialog', dialog => dialog.dismiss());
    await manager.getByRole('button', { name: '重新读取' }).click();
    await expect(manager.getByLabel('商品说明 2')).toHaveValue('未保存的商家说明');
    assert.equal((await manager.goto(`${base}/admin/shop/unknown`)).status(), 404);
    // A revision rollover adds one byte to the saved canonical settings.
    const boundary = await admin.newPage();
    const boundaryProducts = Object.fromEntries(Array.from({ length: 8 }, (_, index) => [String(index + 1), { description: 'a'.repeat(4000), after_sales: 'b'.repeat(3950) }]));
    const boundarySkus = Object.fromEntries(adminSnapshot.items.map(item => [item.key, { price_cents: null, published: false }]));
    const boundaryPayload = { revision: 9, telegram: '', skus: boundarySkus, products: boundaryProducts };
    const boundaryBytes = () => Buffer.byteLength(JSON.stringify(boundaryPayload), 'utf8');
    const headroom = 65536 - boundaryBytes();
    assert.ok(headroom > 0 && headroom < 8000);
    const chinese = Math.floor(headroom / 2);
    boundaryProducts['1'].description = '中'.repeat(chinese) + 'a'.repeat(4000 - chinese);
    if (headroom % 2) boundaryProducts['1'].after_sales += 'z';
    assert.equal(boundaryBytes(), 65536);
    let sentOversize = false;
    await boundary.route('**/api/v1/shop/admin', route => {
      if (route.request().method() === 'GET') return route.fulfill({ json: { ...adminSnapshot, revision: 9, products: boundaryProducts } });
      sentOversize = true;
      return route.fulfill({ status: 200, json: { ...adminSnapshot, revision: 10, products: boundaryProducts } });
    });
    await boundary.goto(`${base}/admin/shop`);
    await expect(boundary.getByRole('heading', { name: /^商品管理/ })).toBeVisible();
    await boundary.getByRole('button', { name: '保存商品设置' }).click();
    await expect(boundary.getByRole('alert')).toContainText('商品设置总内容过长');
    assert.equal(sentOversize, false);
    await boundary.close();
    if (process.env.REACT_SHOP_SCREENSHOT_DIR) {
      const preview = structuredClone(fresh);
      preview.products[0].description = '此处展示商家填写的商品说明。\n购买前请联系商家确认商品规格、账号适用条件与交付方式。';
      preview.products[0].after_sales = '此处展示商家填写的售后条款。请在购买前联系商家了解详情。';
      await page.route('**/api/v1/shop/catalog', route => route.fulfill({ json: preview }));
      await page.setViewportSize({ width: 1440, height: 1000 });
      await page.goto(`${base}/?product=2`);
      await expect(page.getByText('此处展示商家填写的商品说明。', { exact: false })).toBeVisible();
      await page.screenshot({ path: path.join(process.env.REACT_SHOP_SCREENSHOT_DIR, 'detail-preview-1440.png'), fullPage: true });
    }
    await context.close();
    await admin.close();
    console.log('PASS: detail/cart/history/current checkout, responsive layout, merchant copy/privacy/drafts');
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
