const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const base = process.env.PREVIEW_BASE_URL;
    const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, permissions: ['clipboard-write'] });
    await context.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await context.route('**/api/chat/settings', route => route.fulfill({ json: { temperature: 0.7, api_key_configured: true } }));
    await context.route('**/api/chat/models', route => route.fulfill({ json: [{ id: 'preview-model', name: 'Preview model' }] }));
    await page.goto(`${base}/__react/?view=chat`);
    await expect(page.getByRole('heading', { name: '把问题想明白' })).toBeVisible();
    await expect(page.getByLabel('当前模型')).toHaveValue('preview-model');
    await page.getByRole('button', { name: '＋ 项目', exact: true }).click();
    await page.getByRole('button', { name: 'AI 与存储', exact: true }).click();
    await page.getByRole('button', { name: '保存项目', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('button', { name: '选择学习项目：AI 与存储', exact: true })).toBeVisible();
    await page.getByRole('button', { name: /论文资料/ }).click();
    await page.getByLabel('上传论文', { exact: true }).setInputFiles({ name: 'storage-paper.txt', mimeType: 'text/plain', buffer: Buffer.from('LSM Tree turns random writes into sequential writes. Measure write amplification.') });
    await expect(page.getByText('资料已保存，处理完成后可勾选提问。')).toBeVisible();
    await page.getByRole('checkbox').check();
    await page.getByLabel('聊天消息').fill('如何验证写入放大？');
    await page.getByRole('button', { name: '发送 ↑' }).click();
    await expect(page.locator('.chat-message-assistant')).toContainText('LSM Tree');
    await expect(page.locator('.chat-message-assistant table')).toBeVisible();
    await expect(page.locator('.katex')).toHaveCount(1);
    await expect(page.getByRole('button', { name: '保存到记录' })).toBeEnabled();
    await page.getByText('参考原文 · 1 个片段').click();
    await expect(page.locator('.chat-citation blockquote')).toContainText('sequential writes');
    const raw = await page.locator('.chat-citation a').getAttribute('href');
    assert((await context.request.get(`${base}${raw.split('#')[0]}`)).ok());
    const list = await (await context.request.get(`${base}/api/chat/conversations`)).json();
    const conversationId = list.items[0].id;
    await page.getByRole('button', { name: '保存到记录' }).click();
    await expect(page.getByRole('dialog', { name: '保存对话到记录' })).toBeVisible();
    await expect(page.getByLabel('记录类型').locator('option')).toHaveText(['AI / 存储学习', '论文阅读', '雅思练习', '思考变化']);
    await page.getByLabel('记录内容').fill('我需要用实际写入字节量验证写入放大。');
    await page.getByLabel('下一次如何验证或复习').fill('运行一次小规模基准测试');
    await page.getByRole('dialog', { name: '保存对话到记录' }).getByRole('button', { name: '保存到记录' }).click();
    await expect(page.getByText('已保存，可在时间线中继续补充自己的理解。')).toBeVisible();
    await expect(page.getByRole('link', { name: '查看记录' })).toHaveAttribute('href', '/admin/plans#daily-timeline');
    const journal = await (await context.request.get(`${base}/api/journal`)).json();
    assert.equal(journal.items[0].chat_source.conversation_id, conversationId);
    const recordsPage = await context.newPage();
    await recordsPage.goto(`${base}/admin/plans#daily-timeline`);
    await expect(recordsPage.locator('.journal-timeline')).toContainText('我需要用实际写入字节量验证写入放大。');
    await expect(recordsPage.locator('.journal-timeline a')).toHaveAttribute('href', `/admin/chat?conversation=${conversationId}`);
    await expect(recordsPage.getByLabel('记录内容')).toBeVisible();
    await recordsPage.close();
    await page.getByRole('button', { name: '关闭窗口' }).click();
    await page.getByLabel('聊天消息').fill('这是一条跨设备草稿');
    await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible();
    const device = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await device.addCookies([{ name: 'sid', value: process.env.REACT_PREVIEW_ADMIN_COOKIE, url: base }]);
    await device.route('**/api/chat/settings', route => route.fulfill({ json: { temperature: 0.7, api_key_configured: true } }));
    await device.route('**/api/chat/models', route => route.fulfill({ json: [{ id: 'preview-model', name: 'Preview model' }] }));
    const mobile = await device.newPage();
    await mobile.goto(`${base}/admin/chat?conversation=${conversationId}`);
    await expect(mobile.getByLabel('聊天消息')).toHaveValue('这是一条跨设备草稿');
    await expect(mobile.locator('.chat-message-assistant')).toContainText('LSM Tree');
    assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'mobile must fit viewport');
    fs.mkdirSync('test-results/personal-ai', { recursive: true });
    await mobile.screenshot({ path: 'test-results/personal-ai/mobile.png', fullPage: true });
    await page.getByLabel('聊天消息').fill('');
    await expect.poll(async () => (await (await context.request.get(`${base}/api/chat/conversations/${conversationId}`)).json()).draft).toBe('');
    await mobile.getByLabel('聊天消息').fill('另一个设备未同步的草稿');
    await expect(mobile.getByRole('button', { name: '保留本机草稿并保存' })).toBeVisible();
    await expect(mobile.getByLabel('聊天消息')).toHaveValue('另一个设备未同步的草稿');
    assert.equal((await (await context.request.get(`${base}/api/chat/conversations/${conversationId}`)).json()).draft, '');
    await mobile.getByRole('button', { name: '使用服务器草稿' }).click();
    await expect(mobile.getByLabel('聊天消息')).toHaveValue('');
    await mobile.getByRole('button', { name: '打开历史记录' }).click();
    await expect(mobile.locator('.chat-history-panel')).toBeVisible();
    await mobile.getByRole('button', { name: '隐藏', exact: true }).click();
    await page.getByRole('button', { name: '打开历史记录' }).click();
    await page.getByRole('searchbox', { name: '搜索对话' }).fill('sequential');
    await expect(page.locator('.chat-session')).toHaveCount(0); // quotations alone are not searched
    await page.getByRole('searchbox', { name: '搜索对话' }).fill('写入放大');
    await expect(page.locator('.chat-session')).toHaveCount(1);
    await page.screenshot({ path: 'test-results/personal-ai/desktop.png', fullPage: true });
    await page.getByRole('button', { name: '导出', exact: true }).click();
    await page.getByRole('button', { name: '知识库', exact: true }).click();
    await page.getByLabel('搜索知识库', { exact: true }).fill('sequential writes');
    await page.getByRole('button', { name: '语义搜索', exact: true }).click();
    await expect(page.getByRole('dialog').locator('blockquote')).toContainText('sequential writes');
    await page.getByRole('button', { name: '关闭窗口' }).click();
    await page.locator('.chat-message-assistant').getByRole('button', { name: '记入项目' }).click();
    await page.getByLabel('项目记忆内容').fill('用实际字节量核对写入放大，不混淆吞吐量。');
    await page.getByRole('button', { name: '保存记忆', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('用实际字节量核对写入放大，不混淆吞吐量。');
    await page.getByRole('button', { name: '关闭窗口' }).click();
    await page.getByRole('button', { name: '编辑问题', exact: true }).click();
    await page.getByLabel('修改问题').fill('改成验证读取放大？');
    await page.getByRole('button', { name: '创建分支并生成', exact: true }).click();
    await expect(page.locator('.chat-message-user')).toContainText('改成验证读取放大');
    await expect(page.locator('.chat-message-assistant')).toContainText('改成验证读取放大');
    await expect(page.getByRole('button', { name: '返回原对话', exact: true })).toBeEnabled();
    assert.equal(new URL(page.url()).searchParams.get('view'), 'chat', 'branch bookmarks must retain the chat view');
    assert(new URL(page.url()).searchParams.get('conversation'), 'branch bookmarks retain their conversation');
    const original = await (await context.request.get(`${base}/api/chat/conversations/${conversationId}`)).json();
    assert.equal(original.messages[0].content, '如何验证写入放大？');
    assert.equal(original.messages.length, 2);
    await page.getByRole('button', { name: '重新生成', exact: true }).click();
    await page.getByRole('button', { name: '创建分支并生成', exact: true }).click();
    await expect(page.locator('.chat-message-assistant')).toContainText('改成验证读取放大');
    await expect(page.getByRole('button', { name: '重新生成', exact: true })).toBeEnabled();
    await page.locator('.chat-message-assistant').getByRole('button', { name: '从这里分支' }).click();
    await page.getByRole('button', { name: '创建分支', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('.chat-message-assistant')).toHaveCount(1);
    await page.getByRole('button', { name: '长期上下文', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('当前对话暂不需要摘要');
    await page.getByRole('button', { name: '关闭窗口' }).click();
    await page.getByLabel('聊天消息').fill('计算 1、2、3 的均值');
    await page.getByRole('button', { name: '搜索与工具', exact: true }).click();
    await page.getByLabel('工具类型').selectOption('python');
    await page.getByLabel('Python 代码').fill("import numpy as np\nprint('mean =', float(np.mean([1, 2, 3])))\nopen('/workspace/output/mean.txt','w').write('mean=2.0')");
    await page.getByRole('button', { name: '准备调用', exact: true }).click();
    await expect(page.getByText('等待确认', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '确认执行', exact: true }).click();
    await expect(page.getByRole('dialog').locator('.workspace-tool-output pre')).toContainText('mean = 2.0', { timeout: 25000 });
    await expect(page.getByRole('dialog').getByRole('link', { name: /mean.txt/ })).toBeVisible();
    await page.getByRole('button', { name: '附上 1 份结果并返回对话', exact: true }).click();
    await expect(page.getByRole('button', { name: '已附 1 份工具结果 · 移除' })).toBeVisible();
    await page.getByRole('button', { name: '发送 ↑', exact: true }).click();
    await expect(page.locator('.chat-message-assistant')).toHaveCount(2);
    await page.getByText('本次工具结果 · 1', { exact: true }).click();
    await expect(page.locator('.chat-message-assistant .workspace-tool-output')).toContainText('mean = 2.0');
    await page.evaluate(() => localStorage.setItem('hy2.chat.sessions.v1', JSON.stringify([{ id: 'old-browser', messages: [{ role: 'user', content: '旧对话迁移测试' }], updatedAt: Date.now() }])));
    await page.reload();
    await page.getByRole('button', { name: '导入旧对话（1）' }).click();
    await expect(page.getByText(/导入完成：新增 1 个对话/)).toBeVisible();
    await page.reload();
    await page.getByRole('button', { name: '导入旧对话（1）' }).click();
    await expect(page.getByText(/导入完成：新增 0 个对话/)).toBeVisible();
    assert(await page.evaluate(() => localStorage.getItem('hy2.chat.sessions.v1')), 'original legacy data remains');
    assert.deepEqual(errors, []);
    await device.close(); await context.close();
    console.log('Personal AI workspace browser acceptance passed');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
