const assert = require('node:assert/strict');
const fs = require('node:fs');

const page = fs.readFileSync('frontend/src/features/video/VideoPage.tsx', 'utf8');
const storyboard = fs.readFileSync('frontend/src/features/video/VideoStoryboard.tsx', 'utf8');
const types = fs.readFileSync('frontend/src/features/video/videoTypes.ts', 'utf8');
const styles = fs.readFileSync('frontend/src/styles/sections/22-video-storyboard.css', 'utf8');
const canvas = fs.readFileSync('frontend/src/features/video/VideoCanvas.tsx', 'utf8');

assert.match(page, /VideoStoryboard/);
assert.match(storyboard, /video-storyboard/);
assert.match(storyboard, /添加分镜/);
assert.match(storyboard, /运行当前镜头/);
assert.match(page, /storyboard/);
assert.match(page, /run\.workflow\?\.nodes/);
assert.match(page, /useState<'canvas' \| 'storyboard'>\('canvas'\)/);
assert.match(page, /video-canvas-editor-primary/);
assert.match(page, /role="tablist" aria-label="工作区视图"/);
assert.doesNotMatch(page, /canvasOpen/);
assert.doesNotMatch(page, /video-canvas-layer/);
assert.match(page, /refreshCapabilities/);
assert.match(page, /storyboard\.style_prompt/);
assert.match(page, /shot\.scene/);
assert.match(page, /shot\.character/);
assert.match(page, /shot\.shot_type/);
assert.match(page, /image_asset_id/);
assert.match(page, /asset:\/\//);
assert.match(page, /aspect_ratio/);
assert.match(page, /duration: shot\.duration/);
assert.match(page, /if \(!shot\.image_asset_id\)/);
assert.doesNotMatch(page, /VideoSettingsDrawer/);
assert.match(page, /href="\/admin\/services\?tab=ai"/);
assert.match(page, /AI 创作助手/);
assert.match(fs.readFileSync('frontend/src/features/video/VideoCreativeAssistant.tsx', 'utf8'), /应用到当前工作流/);
assert.match(types, /VideoStoryboardShot/);
assert.match(types, /storyboard/);
assert.match(styles, /video-storyboard-row/);
assert.match(canvas, /video-node-palette/);
assert.match(canvas, /application\/video-node/);
assert.match(canvas, /onDropNode/);
assert.match(canvas, /screenToFlowPosition/);
assert.match(canvas, /disabledNodeTypes/);
assert.match(page, /disabledNodeTypes=/);
assert.match(page, /availableTemplates/);
assert.match(page, /VIDEO_TEMPLATES/);
assert.match(page, /video-node-inspector/);
assert.match(page, /selectedNode/);
assert.match(page, /运行工作流/);
assert.match(page, /loadVideoRuns/);
assert.match(page, /video-run-history/);
assert.match(page, /任务记录/);
console.log('video storyboard UI contract passed');
