server {
    listen 80;
    listen [::]:80;
    server_name __HY_SERVER_HOST__ _;
    client_max_body_size 256k;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://__HY_SERVER_HOST__:__HY_HTTPS_PORT__$request_uri;
    }
}
