server {
    listen 80;
    listen [::]:80;
    server_name __HY_SERVER_HOST__;
    if ($host != "__HY_SERVER_HOST__") { return 421; }
    client_max_body_size 256k;
    access_log /var/log/nginx/hysteria-panel.access.log hy2_no_args;
    error_log /var/log/nginx/hysteria-panel.error.log crit;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://__HY_SERVER_HOST__:__HY_HTTPS_PORT__$request_uri;
    }
}
