import { useEffect, useState } from 'react';
import { AdminShell } from '../../../shared/AdminShell';
import { ResourceError, useReadResource } from '../../../shared/readResource';
import { RULES_ENDPOINT, parseRules, saveRules } from './requests';

function ErrorState({ error, retry }: { error: ResourceError; retry: () => void }) { if (error.status === 401) return <div className="card"><div className="err" role="alert">管理员登录已失效。</div><a className="btn secondary mt-md" href="/login">前往登录</a></div>; return <div className="card"><div className="err" role="alert">规则加载失败：{error.message}</div><button className="btn secondary mt-md" type="button" onClick={retry}>重试</button></div>; }
export function RulesPage({ publicHost }: { publicHost: string }) {
  const rules = useReadResource(RULES_ENDPOINT, { validate: parseRules });
  const [draft, setDraft] = useState(''); const [revision, setRevision] = useState(''); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (rules.status === 'success' && !dirty) { setDraft(rules.data.rules.join('\n')); setRevision(rules.data.revision); } }, [rules.status, rules.data, dirty]);
  const save = async () => { setBusy(true); setMessage('正在保存…'); const controller = new AbortController(); try { const result = await saveRules({ rules_raw: draft, template_revision: revision }, controller.signal); if (result.ok) { setRevision(result.revision); setDirty(false); setMessage('路由规则已保存；用户下次拉取订阅时生效'); } else if (result.error === 'revision_conflict') setMessage('模板已被其他操作更新；草稿保留，请刷新后合并'); else setMessage('规则格式无效，服务器未修改'); } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败，请刷新核对'); } finally { setBusy(false); } };
  return <AdminShell active="rules" pageTitle="路由规则" badge={rules.status === 'success' ? `${rules.data.rules.length} 条` : ''} subtitle={`${publicHost} · 订阅匹配顺序`} topbarExtra={<span className="badge poll-status">版本受保护</span>}>
    {rules.status === 'error' ? <ErrorState error={rules.error} retry={rules.retry}/> : null}{rules.status === 'loading' ? <div className="card" role="status">正在加载规则…</div> : null}{rules.status === 'success' ? <div className="admin-page">{message ? <div className="flash" role="status">{message}</div> : null}<section className="form-section"><div className="form-section-title">规则说明</div><div className="form-section-desc">自定义规则按从上到下顺序匹配。每行一条规则，保存时会校验类型、长度和动作。</div><div className="small">当前版本：<code>{revision}</code></div></section><section className="admin-section"><div className="admin-section-header"><h2 className="admin-section-title">当前规则列表</h2></div><div className="admin-section-body"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>#</th><th>规则</th></tr></thead><tbody>{rules.data.rules.length ? rules.data.rules.map((rule, index) => <tr key={`${index}-${rule}`}><th scope="row">{index + 1}</th><td><code>{rule}</code></td></tr>) : <tr><td colSpan={2} className="empty">暂无规则</td></tr>}</tbody></table></div></div></section><section className="code-panel"><div className="code-panel-header"><div className="code-panel-title">直接编辑全部规则</div></div><div className="code-panel-body"><label className="sr-only" htmlFor="rules-raw">全部路由规则</label><textarea id="rules-raw" className="rules-raw-textarea" value={draft} onChange={event => { setDraft(event.target.value); setDirty(true); }} /><div className="row mt-md"><button className="btn btn-primary" type="button" onClick={() => void save()} disabled={busy || !dirty}>覆盖全部规则</button><button className="btn secondary" type="button" onClick={() => { setDraft(rules.data.rules.join('\n')); setRevision(rules.data.revision); setDirty(false); setMessage('已恢复最新版本'); }} disabled={busy || !dirty}>放弃草稿</button></div></div></section></div> : null}
  </AdminShell>;
}

